### ISSUE TITLE
切闪和切医疗针的按键重复

### ISSUE THREAD

**Issue by FutureRainfall** [Purple-CSGO/CS2-Config-Presets#6]
in auto.cfg
**in line 94:** bind x "slot3; slot7"
**in line 97:** bind x "slot12"

**Comment by FutureRainfall** [comment]
![PixPin_2024-04-29_09-55-47](https://github.com/Purple-CSGO/CS2-Config-Presets/assets/39761362/b646d499-6cfa-4f6a-8ed8-3a88315cde98)

**Comment by Purp16** [comment]
这个是还原了默认的按键，使用哪个指令和处理按键冲突是用户解决的
