### ISSUE TITLE
罗技 GPW2，win10 最新系统，前侧键使用麦克风绑定 mouse5，进游戏就成了 mouse4，而且这两个按键都能讲话

### ISSUE THREAD

**Issue by HelIwalker** [Purple-CSGO/CS2-Config-Presets#7]
![image](https://github.com/user-attachments/assets/86b4c4f6-9890-49ca-80e5-6e18f114ed25)
![image](https://github.com/user-attachments/assets/42f6e78b-a4fc-44b0-b5f5-9b9329b32e81)

**Comment by Purple-CSGO** [comment]
可能你的鼠标两个侧键定义不一样？
